services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - ${MINIO_CLIENT_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env
volumes:
  minio-storage: