services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - shared-network

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
    networks:
      - shared-network

  minify:
    image: minify
    environment:
      HOSTNAME_DB: db
      HOSTNAME_MINIO: minio
    ports:
      - ${MINIFY_PORT}:8080
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true