services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_CLIENT_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  minio-storage: