spring:
  application:
    name: "minify"

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}

minio:
  url: ${MINIO_URL}
  bucket: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}