create table files
(
    id                 bigint primary key generated by default as identity,
    filename           varchar not null,
    file_original_name varchar not null,
    file_path          varchar not null,
    content_type       varchar not null,
    size               bigint  not null
);